# Generated by Django 2.1.2 on 2018-10-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRealty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('realty', models.CharField(max_length=100)),
                ('url_realty', models.CharField(max_length=1000)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'catalog_realty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationStateKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'communication_state_kinds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField()),
                ('key', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('server_key', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('kind', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Файл земельного участка',
                'verbose_name_plural': 'Файлы земельных участков',
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filesoks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField()),
                ('key', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('server_key', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('kind', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Файл объекта капитального строительства',
                'verbose_name_plural': 'Файлы объектов капитального строительства',
                'db_table': 'filesoks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_updated', models.DateTimeField()),
                ('is_parsed', models.BooleanField()),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('source_url', models.CharField(max_length=2000)),
                ('raw_price', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_area', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('raw_address', models.TextField(blank=True, null=True)),
                ('raw_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('source_date_added', models.DateTimeField(blank=True, null=True)),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Цена')),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Площадь')),
                ('address_info', models.TextField(blank=True, null=True)),
                ('cadastre_number', models.CharField(blank=True, max_length=50, null=True)),
                ('communications', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_recurrence', models.IntegerField(blank=True, null=True)),
                ('kladr', models.CharField(blank=True, max_length=50, null=True)),
                ('locality', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(blank=True, max_length=500, null=True)),
                ('official_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Земельный участок',
                'verbose_name_plural': 'Земельные участки',
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordOks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_updated', models.DateTimeField()),
                ('is_parsed', models.BooleanField()),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('source_url', models.CharField(max_length=2000)),
                ('raw_price', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_area', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('raw_address', models.TextField(blank=True, null=True)),
                ('raw_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('source_date_added', models.DateTimeField(blank=True, null=True)),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Цена')),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Площадь')),
                ('address_info', models.TextField(blank=True, null=True)),
                ('cadastre_number', models.CharField(blank=True, max_length=50, null=True)),
                ('communications', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Объект капитального строительства',
                'verbose_name_plural': 'Объекты капитального строительства',
                'db_table': 'recordsoks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RightsKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'rights_kinds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpiderUpdates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('hash', models.CharField(max_length=200)),
                ('size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spider_updates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsageKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Разрешенное использование',
                'verbose_name_plural': 'Разрешенное использование',
                'db_table': 'usage_kinds',
                'managed': False,
            },
        ),
    ]
